<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Admin Panel</title>
		<link href="css/schedules.css" rel="stylesheet">
	</head>
	<body>
		<div id="header">
			<h3>Schedules</h3>
		</div>
		<?php
		  include('sidebar.php')
		?>
		<div id="section">
			<br><br>
            <h3>Class1 Schedule</h3>
			<table style="width:100%">
                <tr>
                    <th>Days / Lectures</th>
                    <th>Lecture1</th>
                    <th>Lecture2</th>		
                    <th>Lecture3</th>
                    <th>Lecture4</th>
                    <th>Lecture5</th>
                    <th>Lecture6</th>
                </tr>
                <tr>
                    <td>Saturday</td>
                    <td>Arabic</td>
                    <td>English</td>        
                    <td>Math</td>
                    <td>Physics</td>      
                    <td>Chemistry</td>
                    <td>Painting</td>
                </tr>
                <tr>
                    <td>Sunday</td>
                    <td>Arabic</td>
                    <td>English</td>        
                    <td>Math</td>
                    <td>Physics</td>      
                    <td>Chemistry</td>
                    <td>Painting</td>
                </tr>
                <tr>
                    <td>Monday</td>
                    <td>Arabic</td>
                    <td>English</td>        
                    <td>Math</td>
                    <td>Physics</td>      
                    <td>Chemistry</td>
                    <td>Painting</td>
                </tr>
                <tr>
                    <td>Teusday</td>
                    <td>Arabic</td>
                    <td>English</td>        
                    <td>Math</td>
                    <td>Physics</td>      
                    <td>Chemistry</td>
                    <td>Painting</td>
                </tr>
                <tr>
                    <td>Wednesday</td>
                    <td>Arabic</td>
                    <td>English</td>        
                    <td>Math</td>
                    <td>Physics</td>      
                    <td>Chemistry</td>
                    <td>Painting</td>
                </tr>
                <tr>
                    <td>Thursday</td>
                    <td>Arabic</td>
                    <td>English</td>        
                    <td>Math</td>
                    <td>Physics</td>      
                    <td>Chemistry</td>
                    <td>Painting</td>
                </tr>
        </table>
        <br><br>
        <h3>Class2 Schedule</h3>
			<table style="width:100%">
                <tr>
                    <th>Days / Lectures</th>
                    <th>Lecture1</th>
                    <th>Lecture2</th>		
                    <th>Lecture3</th>
                    <th>Lecture4</th>
                    <th>Lecture5</th>
                    <th>Lecture6</th>
                </tr>
                <tr>
                    <td>Saturday</td>
                    <td>Arabic</td>
                    <td>English</td>        
                    <td>Math</td>
                    <td>Physics</td>      
                    <td>Chemistry</td>
                    <td>Painting</td>
                </tr>
                <tr>
                    <td>Sunday</td>
                    <td>Arabic</td>
                    <td>English</td>        
                    <td>Math</td>
                    <td>Physics</td>      
                    <td>Chemistry</td>
                    <td>Painting</td>
                </tr>
                <tr>
                    <td>Monday</td>
                    <td>Arabic</td>
                    <td>English</td>        
                    <td>Math</td>
                    <td>Physics</td>      
                    <td>Chemistry</td>
                    <td>Painting</td>
                </tr>
                <tr>
                    <td>Teusday</td>
                    <td>Arabic</td>
                    <td>English</td>        
                    <td>Math</td>
                    <td>Physics</td>      
                    <td>Chemistry</td>
                    <td>Painting</td>
                </tr>
                <tr>
                    <td>Wednesday</td>
                    <td>Arabic</td>
                    <td>English</td>        
                    <td>Math</td>
                    <td>Physics</td>      
                    <td>Chemistry</td>
                    <td>Painting</td>
                </tr>
                <tr>
                    <td>Thursday</td>
                    <td>Arabic</td>
                    <td>English</td>        
                    <td>Math</td>
                    <td>Physics</td>      
                    <td>Chemistry</td>
                    <td>Painting</td>
                </tr>
        </table>
        <br><br>
        <h3>Class3 Schedule</h3>
			<table style="width:100%">
                <tr>
                    <th>Days / Lectures</th>
                    <th>Lecture1</th>
                    <th>Lecture2</th>		
                    <th>Lecture3</th>
                    <th>Lecture4</th>
                    <th>Lecture5</th>
                    <th>Lecture6</th>
                </tr>
                <tr>
                    <td>Saturday</td>
                    <td>Arabic</td>
                    <td>English</td>        
                    <td>Math</td>
                    <td>Physics</td>      
                    <td>Chemistry</td>
                    <td>Painting</td>
                </tr>
                <tr>
                    <td>Sunday</td>
                    <td>Arabic</td>
                    <td>English</td>        
                    <td>Math</td>
                    <td>Physics</td>      
                    <td>Chemistry</td>
                    <td>Painting</td>
                </tr>
                <tr>
                    <td>Monday</td>
                    <td>Arabic</td>
                    <td>English</td>        
                    <td>Math</td>
                    <td>Physics</td>      
                    <td>Chemistry</td>
                    <td>Painting</td>
                </tr>
                <tr>
                    <td>Teusday</td>
                    <td>Arabic</td>
                    <td>English</td>        
                    <td>Math</td>
                    <td>Physics</td>      
                    <td>Chemistry</td>
                    <td>Painting</td>
                </tr>
                <tr>
                    <td>Wednesday</td>
                    <td>Arabic</td>
                    <td>English</td>        
                    <td>Math</td>
                    <td>Physics</td>      
                    <td>Chemistry</td>
                    <td>Painting</td>
                </tr>
                <tr>
                    <td>Thursday</td>
                    <td>Arabic</td>
                    <td>English</td>        
                    <td>Math</td>
                    <td>Physics</td>      
                    <td>Chemistry</td>
                    <td>Painting</td>
                </tr>
        </table>
		</div>
	</body>
</html>
